### ISSUE TITLE
Naming note

### ISSUE THREAD

**Issue by vatterspun** [alexporrello/UnDuplicate#1]
Not sure how important this is, but there are a number of the projects named "UnDuplicate" just on Github, so it might make sense to call it APUnDuplicate (your initials) or something similar.

It doesn't really matter until one of those projects takes off in a big way and causes confusion (e.g. back when Firefox tried to call itself Firebird, there was already a popular database app called Firebird).

**Comment by alexporrello** [comment]
Thanks for the suggestion, but I'm going to leave the name as-is.

**Comment by vatterspun** [comment]
No prob
